<?php

namespace Database\Seeders;

use App\Models\Ticket;
use Illuminate\Database\Seeder;

class TicketSeeder extends Seeder
{
    public function run(): void
    {
        $tickets = [
            [
                'subject' => 'Cannot login to account',
                'body' => 'I forgot my password and cannot access my account.',
                'status' => 'open',
                'category' => 'Account',
                'explanation' => 'The customer has an account login problem.',
                'confidence' => 0.92,
                'internal_note' => 'Password reset may be required.',
            ],
            [
                'subject' => 'Payment failed',
                'body' => 'My payment was declined when I tried to purchase the plan.',
                'status' => 'open',
                'category' => 'Billing',
                'explanation' => 'The issue is related to a failed payment.',
                'confidence' => 0.95,
                'internal_note' => 'Check payment gateway logs.',
            ],
            [
                'subject' => 'Website showing error',
                'body' => 'I see a 500 error when opening the dashboard.',
                'status' => 'in_progress',
                'category' => 'Technical',
                'explanation' => 'The customer is reporting a technical server error.',
                'confidence' => 0.96,
                'internal_note' => 'Developer is investigating the server error.',
            ],
            [
                'subject' => 'How can I change my email?',
                'body' => 'I want to update the email address connected to my account.',
                'status' => 'open',
                'category' => 'Account',
                'explanation' => 'The request concerns account information.',
                'confidence' => 0.91,
                'internal_note' => null,
            ],
            [
                'subject' => 'Refund request',
                'body' => 'I was charged twice and would like a refund.',
                'status' => 'in_progress',
                'category' => 'Billing',
                'explanation' => 'The customer is requesting a refund for duplicate billing.',
                'confidence' => 0.97,
                'internal_note' => 'Verify duplicate transaction.',
            ],
            [
                'subject' => 'App is crashing',
                'body' => 'The mobile application closes whenever I open the profile page.',
                'status' => 'open',
                'category' => 'Technical',
                'explanation' => 'The mobile application is experiencing a technical crash.',
                'confidence' => 0.94,
                'internal_note' => null,
            ],
            [
                'subject' => 'Unable to upload file',
                'body' => 'The document upload keeps failing with an error.',
                'status' => 'in_progress',
                'category' => 'Technical',
                'explanation' => 'The problem is related to file uploading.',
                'confidence' => 0.93,
                'internal_note' => 'Check upload size limitation.',
            ],
            [
                'subject' => 'Subscription price question',
                'body' => 'Can you explain the current subscription pricing?',
                'status' => 'open',
                'category' => 'Billing',
                'explanation' => 'The customer is asking about subscription pricing.',
                'confidence' => 0.89,
                'internal_note' => null,
            ],
            [
                'subject' => 'Account locked',
                'body' => 'My account has been locked after several login attempts.',
                'status' => 'resolved',
                'category' => 'Account',
                'explanation' => 'The account has been locked due to login attempts.',
                'confidence' => 0.96,
                'internal_note' => 'Account unlocked successfully.',
            ],
            [
                'subject' => 'Slow dashboard',
                'body' => 'The dashboard takes a very long time to load.',
                'status' => 'open',
                'category' => 'Technical',
                'explanation' => 'The customer reports a performance issue.',
                'confidence' => 0.90,
                'internal_note' => null,
            ],
            [
                'subject' => 'Need invoice',
                'body' => 'Please send me the invoice for my latest payment.',
                'status' => 'resolved',
                'category' => 'Billing',
                'explanation' => 'The customer is requesting a billing invoice.',
                'confidence' => 0.94,
                'internal_note' => 'Invoice sent to customer.',
            ],
            [
                'subject' => 'Change username',
                'body' => 'I would like to change my username.',
                'status' => 'open',
                'category' => 'Account',
                'explanation' => 'The request concerns account profile information.',
                'confidence' => 0.88,
                'internal_note' => null,
            ],
            [
                'subject' => 'API not responding',
                'body' => 'Our API requests are timing out.',
                'status' => 'in_progress',
                'category' => 'Technical',
                'explanation' => 'The API is experiencing a technical availability issue.',
                'confidence' => 0.97,
                'internal_note' => 'Check API server logs.',
            ],
            [
                'subject' => 'General product question',
                'body' => 'What features are included in the basic plan?',
                'status' => 'open',
                'category' => 'General',
                'explanation' => 'The customer is asking a general product question.',
                'confidence' => 0.87,
                'internal_note' => null,
            ],
            [
                'subject' => 'Card charged but order failed',
                'body' => 'My card was charged but the order was not created.',
                'status' => 'in_progress',
                'category' => 'Billing',
                'explanation' => 'The issue involves a payment and failed order.',
                'confidence' => 0.96,
                'internal_note' => 'Check transaction status.',
            ],
            [
                'subject' => 'Password reset email not received',
                'body' => 'I requested a password reset but did not receive the email.',
                'status' => 'open',
                'category' => 'Account',
                'explanation' => 'The customer cannot complete password recovery.',
                'confidence' => 0.95,
                'internal_note' => null,
            ],
            [
                'subject' => 'Broken page layout',
                'body' => 'The settings page layout is broken on my browser.',
                'status' => 'open',
                'category' => 'Technical',
                'explanation' => 'The customer reports a website UI issue.',
                'confidence' => 0.91,
                'internal_note' => 'Check browser compatibility.',
            ],
            [
                'subject' => 'Cancel subscription',
                'body' => 'I want to cancel my current subscription.',
                'status' => 'resolved',
                'category' => 'Billing',
                'explanation' => 'The customer wants to cancel a paid subscription.',
                'confidence' => 0.93,
                'internal_note' => 'Subscription cancelled.',
            ],
            [
                'subject' => 'Profile information update',
                'body' => 'I need to update my phone number in my profile.',
                'status' => 'open',
                'category' => 'Account',
                'explanation' => 'The request is related to account profile information.',
                'confidence' => 0.92,
                'internal_note' => null,
            ],
            [
                'subject' => 'Server connection error',
                'body' => 'The application cannot connect to the server.',
                'status' => 'in_progress',
                'category' => 'Technical',
                'explanation' => 'The application is experiencing a server connection problem.',
                'confidence' => 0.98,
                'internal_note' => 'Infrastructure team notified.',
            ],
            [
                'subject' => 'Question about service',
                'body' => 'I would like more information about your service.',
                'status' => 'open',
                'category' => 'General',
                'explanation' => 'The customer is requesting general information.',
                'confidence' => 0.85,
                'internal_note' => null,
            ],
            [
                'subject' => 'Unexpected charge',
                'body' => 'I noticed an unexpected charge on my account.',
                'status' => 'open',
                'category' => 'Billing',
                'explanation' => 'The customer is reporting an unexpected billing charge.',
                'confidence' => 0.94,
                'internal_note' => 'Review billing history.',
            ],
            [
                'subject' => 'Two factor authentication problem',
                'body' => 'I cannot receive my two factor authentication code.',
                'status' => 'in_progress',
                'category' => 'Account',
                'explanation' => 'The customer has an account authentication problem.',
                'confidence' => 0.96,
                'internal_note' => null,
            ],
            [
                'subject' => 'Search not working',
                'body' => 'The ticket search function returns no results.',
                'status' => 'open',
                'category' => 'Technical',
                'explanation' => 'The customer reports a technical search problem.',
                'confidence' => 0.92,
                'internal_note' => 'Check search query implementation.',
            ],
            [
                'subject' => 'Thank you for support',
                'body' => 'Thank you for helping me resolve my issue.',
                'status' => 'closed',
                'category' => 'General',
                'explanation' => 'The customer is providing general feedback.',
                'confidence' => 0.84,
                'internal_note' => 'Positive customer feedback.',
            ],
        ];

        foreach ($tickets as $ticket) {
            Ticket::create($ticket);
        }
    }
}